name: Docs

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
            pip install Sphinx sphinx_rtd_theme

      - name: Run tests
        run: |
          sphinx-build -nW -b html -d docs/build/doctrees docs docs/build/html
